# Auto-generated Terraform — test-rup (Azure)
# Generated by AI Infrastructure Agent

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
    
  }

  backend "azurerm" {
    resource_group_name  = "test-rup-tfstate-rg"
    storage_account_name = "testruptfstate"
    container_name       = "tfstate"
    key                  = "test-rup.terraform.tfstate"
  }
}

provider "azurerm" {
  features {}
}



resource "azurerm_resource_group" "main" {
  name     = "test-rup-rg"
  location = "centralindia"
  tags = {
    Project   = "test-rup"
    ManagedBy = "terraform"
  }
}




# ── Virtual Machine ─────────────────────────────────────────────────
resource "azurerm_public_ip" "app" {
  name                = "test-rup-pip"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_network_interface" "app" {
  name                = "test-rup-nic"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  ip_configuration {
    name                          = "internal"
    
    subnet_id                     = null # add a VNet/subnet if this VM needs networking
    
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.app.id
  }
}

resource "azurerm_linux_virtual_machine" "app" {
  name                = "test-rup-vm"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  size                = "Standard_B1s"
  admin_username      = "azureuser"

  network_interface_ids = [azurerm_network_interface.app.id]

  admin_ssh_key {
    username   = "azureuser"
    public_key = file("~/.ssh/id_rsa.pub") # replace with your own key path/variable
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts"
    version   = "latest"
  }

  tags = { Project = "test-rup" }
}

output "vm_public_ip" {
  value       = azurerm_public_ip.app.ip_address
  description = "Public IP of the virtual machine"
}












